services:
    oai-gnb3:
        image: ran-gnb:nrppa_procedures_srs
        privileged: true
        container_name: oai-gnb3
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --sa --thread-pool 3,5,7,9,11
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - /home/eurecom/adeel/geo5g/script/gnb3.9bitCompr.sa.band77.273prb.fhi72.4x4-vvdn_coreoai.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/hugepages:/dev/hugepages
        cpuset: "0,2,3,4,5,6,7,8,9,10,11"
        networks:
            oai-net:
                ipv4_address: 172.21.18.20
        healthcheck:
           test: /bin/bash -c "pgrep nr-softmodem"
           interval: 10s
           timeout: 5s
           retries: 5
    oai-gnb1:
        image: ran-gnb:nrppa_procedures_srs
        privileged: true
        container_name: oai-gnb1
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --sa --thread-pool 13,15,17,19,21
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - /home/eurecom/adeel/geo5g/script/gnb1.9bitCompr.sa.band77.273prb.fhi72.4x4-vvdn_coreoai.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/hugepages:/dev/hugepages
        cpuset: "0,12,13,14,15,16,17,18,19,20,21"
        networks:
            oai-net:
                ipv4_address: 172.21.18.21
        healthcheck:
           test: /bin/bash -c "pgrep nr-softmodem"
           interval: 10s
           timeout: 5s
           retries: 5
networks:
    oai-net:
        driver: macvlan
        name: oai-net
        ipam:
            config:
                - subnet: "172.21.16.0/22"
                  ip_range: "172.21.18.20/32"
                  gateway: "172.21.19.254"
        driver_opts:
            com.docker.network.bridge.name: "oai-net"
            parent: bond0
